name: 'Load Platform Config'
inputs:
  platform:
    required: true
  config:
    required: true
outputs:
  flows:
    required: true
  edge:
    required: true
  shield:
    required: true
  dai:
    required: true
runs:
  using: 'node20'
  main:  'index.js'