name: Test Manual Workflow
env:
  REGISTRY: ghcr.io
  REPO: ${{ format('ghcr.io/{0}/test-gha', github.repository_owner) }}

on:
  workflow_dispatch:
    inputs:
      bu:
        type: string
        required: true
        default: 'news'
      environment:
        type: string
        required: true
        default: 'dev'

jobs:
  test-job:
    name: Test job (configuration extraction)
    runs-on: ubuntu-latest
    environment: ${{ inputs.bu }}-${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Load platform config
        id:   platform
        run: |
          #!/bin/bash
          
          echo "FLOWS=$(cat config/platforms.json | jq '.["${{ inputs.bu }}"].flows | @json')" >> "$GITHUB_OUTPUT"
          echo "EDGE=$(cat config/platforms.json | jq '.["${{ inputs.bu }}"].edge | @json')" >> "$GITHUB_OUTPUT"
          echo "SHIELD=$(cat config/platforms.json | jq '.["${{ inputs.bu }}"].shield | @json')" >> "$GITHUB_OUTPUT"
          echo "DAI=$(cat config/platforms.json | jq '.["${{ inputs.bu }}"].dai | @json')" >> "$GITHUB_OUTPUT"
      - name: Print
        env:
          CFG: ${{steps.platform.outputs.FLOWS}}
        run: |
          #!/bin/bash
          
          # printenv
          echo "$ENV_VAR"
          echo "$CFG"
      
