name: Test Manual Workflow
env:
  REGISTRY: ghcr.io
  REPO: ${{ format('ghcr.io/{0}/test-gha', github.repository_owner) }}

on:
  workflow_dispatch:
    inputs:
      bu:
        type: string
        required: true
        default: 'news'
      environment:
        type: string
        required: true
        default: 'dev'

jobs:
  test-job:
    name: Test job (configuration extraction)
    runs-on: ubuntu-latest
    environment: ${{ inputs.bu }}-${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Load platform config
        id:   platform
        uses: ./.github/actions/platform-load
        with:
          config: config/platforms.json
          platform: ${{ inputs.bu }}
      - name: Print
        env:
          ENV_VAR: ${{vars.ENV_VAR}}
          CFG: ${{steps.platform.dai}}
        run: |
          #!/bin/bash
          
          # printenv
          echo "$ENV_VAR"
          echo "$CFG"
      
