name: Test Manual Workflow
env:
  REGISTRY: ghcr.io
  REPO: ${{ format('ghcr.io/{0}/test-gha', github.repository_owner) }}

on:
  workflow_dispatch:
    inputs:
      bu:
        type: string
        required: true
        default: 'news'
      environment:
        type: string
        required: true
        default: 'dev'

jobs:
  test-job:
    name: Test job (configuration extraction)
    runs-on: ubuntu-latest
    environment: ${{ inputs.bu }}-${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # - name: npm install
      #   working-directory: ./.github/workflows/actions/platform-load
      #   run: |
      #     npm install
      # - name: Load platform config
      #   id:   platform
      #   uses: ./.github/workflows/actions/platform-load
      #   with:
      #     config: config/platforms.json
      #     platform: ${{ inputs.bu }}
      - name: Load platform config
        id:   platform
        run: |
          #!/bin/bash
          
          # cat config/platforms.json | jq '.["news"].flows  | @json
          # cat config/platforms.json | jq '.["news"].edge   | @json
          # cat config/platforms.json | jq '.["news"].shield | @json
          # cat config/platforms.json | jq '.["news"].dai    | @json
          
          # echo "FLOWS=$(cat config/platforms.json | jq '.["news"].flows  | @json)" >> "$GITHUB_OUTPUT"
          echo "DAI=$(cat config/platforms.json | jq '.["news"].dai  | @json')" >> "$GITHUB_OUTPUT"
      - name: Print
        env:
          ENV_VAR: ${{vars.ENV_VAR}}
          CFG: ${{steps.platform.outputs.DAI}}
        run: |
          #!/bin/bash
          
          # printenv
          echo "$ENV_VAR"
          echo $CFG
      
